quarkus:
  otel:
    enabled: true
    exporter:
      otlp:
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
        traces:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
        protocol: http/protobuf
    resource:
      attributes: service.name=spike-center-backend

  oidc:
    realm: master
    auth-server-url: https://identity.spike.center/realms/master
    client-id: spike-center-connect
    application-type: service
    token:
      #      audience: spike-center-connect
      principal-claim: preferred_username
      issuer: https://identity.spike.center/realms/master
    roles:
      role-claim-path: realm_access/roles

  http:
    cors: true
    cors-allowed-origins: "*"
    cors-allowed-methods: "*"
  devservices:
    enabled: false
  log:
    category:
      "io.quarkus.oidc":
        level: DEBUG
      "io.smallrye.jwt":
        level: DEBUG

  datasource:
    db-kind: postgresql
    username: ${DB_USER:spike}
    password: ${DB_PASSWORD:spike}
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spike}

  flyway:
    active: true
    migrate-at-start: true
    locations: db/migration
    schemas: public
    clean-disabled: false # turn on in prod
    baseline-on-migrate: true

tba:
  api:
    key: vH2P21mMVrkygXcQjKVn5i5CSP3fGYHhscFT1Ss57g1NwMkFh6mfabgciyV6ZSSq